oauth2:
    client:
        id: dsrmifotech_client_id_dev
        secret: e6ymuymv4BAU3IadQ6UdMMLwtygdjBW4
    token:
        url: http://localhost:8081/realms/master/protocol/openid-connect/token
server:
    port: 8085

spring:
  application:
    name: external-api-call
  cloud:
    circuitbreaker:
      resilience4j:
        instances:
          externalApiService:
            slidingWindowSize: 10
            failureRateThreshold: 50
            waitDurationInOpenState: 10000
